@echo off

start "DGDR Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\dgdr && python .\realtime_and_backtest_hyperparameter_search_optuna.py --dataset-id month --lookahead-bars 1 --method final_close --min-signal-density 0.1  --put-strike-pct 0.99 --call-strike-pct 1. --n-trials 99999 --timeout 3600 --train-ratio 0.90 --signal-type buy --output-dir month_perspective --optuna-storage sqlite:///month_perspective\\month_month_buy_099.db --optuna-study-name doesnotmatter"

start "DGDR Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\dgdr && python .\realtime_and_backtest_hyperparameter_search_optuna.py --dataset-id month --lookahead-bars 1 --method final_close --min-signal-density 0.1  --put-strike-pct 0.98 --call-strike-pct 1. --n-trials 99999 --timeout 3600 --train-ratio 0.90 --signal-type buy --output-dir month_perspective --optuna-storage sqlite:///month_perspective\\month_month_buy_098.db --optuna-study-name doesnotmatter"

start "DGDR Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\dgdr && python .\realtime_and_backtest_hyperparameter_search_optuna.py --dataset-id month --lookahead-bars 1 --method final_close --min-signal-density 0.1  --put-strike-pct 0.97 --call-strike-pct 1. --n-trials 99999 --timeout 3600 --train-ratio 0.90 --signal-type buy --output-dir month_perspective --optuna-storage sqlite:///month_perspective\\month_month_buy_097.db --optuna-study-name doesnotmatter"

start "DGDR Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\dgdr && python .\realtime_and_backtest_hyperparameter_search_optuna.py --dataset-id month --lookahead-bars 1 --method final_close --min-signal-density 0.1  --put-strike-pct 0.96 --call-strike-pct 1. --n-trials 99999 --timeout 3600 --train-ratio 0.90 --signal-type buy --output-dir month_perspective --optuna-storage sqlite:///month_perspective\\month_month_buy_096.db --optuna-study-name doesnotmatter"

start "DGDR Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\dgdr && python .\realtime_and_backtest_hyperparameter_search_optuna.py --dataset-id month --lookahead-bars 1 --method final_close --min-signal-density 0.1  --put-strike-pct 0.95 --call-strike-pct 1. --n-trials 99999 --timeout 3600 --train-ratio 0.90 --signal-type buy --output-dir month_perspective --optuna-storage sqlite:///month_perspective\\month_month_buy_095.db --optuna-study-name doesnotmatter"