@echo off

start "Prime RSI Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\prime_rsi && python .\realtime_and_backtest_hyperparameter_search_optuna.py --optimize --n-trials 99999 --timeout 80000 --dataset-id month --min-signal-density 0.15 --lookahead-bars 1 --train-ratio 0.8 --optuna-db month_perspective\month_month.db --output-dir month_perspective --optimize-target buy_wr --method final_close --put-strike-pct 0.95 --call-strike-pct 1."
timeout /t 10 /nobreak
start "Prime RSI Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\prime_rsi && python .\realtime_and_backtest_hyperparameter_search_optuna.py --optimize --n-trials 99999 --timeout 80000 --dataset-id month --min-signal-density 0.15 --lookahead-bars 2 --train-ratio 0.8 --optuna-db month_perspective\2month_month.db --output-dir month_perspective --optimize-target buy_wr --method final_close --put-strike-pct 0.95 --call-strike-pct 1."
timeout /t 10 /nobreak
start "Prime RSI Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\prime_rsi && python .\realtime_and_backtest_hyperparameter_search_optuna.py --optimize --n-trials 99999 --timeout 80000 --dataset-id month --min-signal-density 0.15 --lookahead-bars 3 --train-ratio 0.8 --optuna-db month_perspective\3month_month.db --output-dir month_perspective --optimize-target buy_wr --method final_close --put-strike-pct 0.95 --call-strike-pct 1."
timeout /t 10 /nobreak
start "Prime RSI Optuna Month-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\prime_rsi && python .\realtime_and_backtest_hyperparameter_search_optuna.py --optimize --n-trials 99999 --timeout 80000 --dataset-id month --min-signal-density 0.15 --lookahead-bars 4 --train-ratio 0.8 --optuna-db month_perspective\4month_month.db --output-dir month_perspective --optimize-target buy_wr --method final_close --put-strike-pct 0.95 --call-strike-pct 1."
timeout /t 10 /nobreak
start "Prime RSI Optuna Week-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\prime_rsi && python .\realtime_and_backtest_hyperparameter_search_optuna.py --optimize --n-trials 99999 --timeout 80000 --dataset-id week --min-signal-density 0.15 --lookahead-bars 4 --train-ratio 0.7 --optuna-db month_perspective\week_month.db --output-dir month_perspective --optimize-target buy_wr --method final_close --put-strike-pct 0.95 --call-strike-pct 1."
timeout /t 10 /nobreak
start "Prime RSI Optuna Day-Month" cmd /K "call conda activate PY312_HT && cd ..\..\..\src\optimizers\prime_rsi && python .\realtime_and_backtest_hyperparameter_search_optuna.py --optimize --n-trials 99999 --timeout 80000 --dataset-id day --min-signal-density 0.075 --lookahead-bars 20 --train-ratio 0.7 --optuna-db month_perspective\day_month.db --output-dir month_perspective --optimize-target buy_wr --method final_close --put-strike-pct 0.95 --call-strike-pct 1."
timeout /t 10 /nobreak